=== ACS-Community/ACS/LGPL/CommonSoftware/acserr/ws/idl/ACSError.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by Bogdan Jeram (European Southern Observatory) -->
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Bogdan Jeram (E.S.O.) -->
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<!--
  Here we cannot have now the targetNamespace, because this would 
  introduce a major backward incompatibility.
  See SPR.: 2006xxxxx
  <xs:schema targetNamespace="Alma/ACSError"
	   xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   elementFormDefault="qualified" 
	   attributeFormDefault="unqualified">
	-->
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified"
        attributeFormDefault="unqualified">

	<!-- types definition -->
	<xs:simpleType name="ErrorType">
		<xs:restriction base="xs:nonNegativeInteger"/>
	</xs:simpleType>
	<xs:simpleType name="ErrorCode">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- non empty string -->
	<xs:simpleType name="nonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- short description string. Maximal length is 50. If you chang it ,code has to be changed, too !!! -->
	<xs:simpleType name="shortDescriptionString">
		<xs:restriction base="nonEmptyString">
			<xs:minLength value="1"/>
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MemberTypes">
		<xs:restriction base="nonEmptyString">
			<xs:enumeration value="double"/>
			<xs:enumeration value="long"/>
			<xs:enumeration value="string"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Type">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="Code" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Member" type="Member_"/>
						</xs:choice>
						<xs:attribute name="name" type="nonEmptyString" use="required"/>
						<xs:attribute name="shortDescription" type="shortDescriptionString" use="required"/>
						<xs:attribute name="description" type="nonEmptyString" use="required"/>
						<xs:attribute name="URL" type="xs:string" use="optional"/>
						<!-- 						<xs:attribute name="code" type="ErrorCode" use="required"/> -->
					</xs:complexType>
					<xs:unique name="uniqueCodeMember">
						<xs:selector xpath="./Member"/>
						<xs:field xpath="@name"/>
					</xs:unique>
				</xs:element>
				<xs:element name="ErrorCode" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Member" type="Member_"/>
						</xs:choice>
						<xs:attribute name="name" type="nonEmptyString" use="required"/>
						<xs:attribute name="shortDescription" type="shortDescriptionString" use="required"/>
						<xs:attribute name="description" type="nonEmptyString" use="required"/>
						<xs:attribute name="URL" type="xs:string" use="optional"/>
						<xs:attribute name="_suppressExceptionGeneration" type="xs:boolean" default="false"/>
						<!-- 						<xs:attribute name="code" type="ErrorCode" use="required"/> -->
					</xs:complexType>
					<xs:unique name="uniqueErrorCodeMember">
						<xs:selector xpath="./Member"/>
						<xs:field xpath="@name"/>
					</xs:unique>
				</xs:element>
			</xs:choice>
			<xs:attribute name="name" type="nonEmptyString" use="required"/>
			<xs:attribute name="type" type="ErrorType" use="required"/>
			<xs:attribute name="shortDescription" type="shortDescriptionString" use="optional"/>
			<xs:attribute name="description" type="nonEmptyString" use="optional"/>
			<xs:attribute name="URL" type="xs:string" use="optional"/>
			<xs:attribute name="_prefix" type="xs:string" default="alma"/>
		</xs:complexType>
		<xs:unique name="uniqueErrorCode">
			<xs:selector xpath="./ErrorCode|./Code"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<!-- code/errocode name has to be unique -->
	</xs:element>
	<xs:complexType name="Member_">
		<xs:attribute name="name" type="nonEmptyString" use="required"/>
		<xs:attribute name="type" type="MemberTypes" use="required"/>
		<xs:attribute name="description" type="nonEmptyString" use="optional"/>
	</xs:complexType>
</xs:schema>

=== ACS-Community/ACS/LGPL/CommonSoftware/monitoring/monicd/ws/idl/MonitorErr.xml
<Type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="Alma/ACSError" xsi:schemaLocation="Alma/ACSError ACSError.xsd" 
	name="MonitorErr" type="60200" _prefix="alma">

	<!-- =========== Monitor collector errors =========== -->
	
	<ErrorCode name="DeviceAlreadyRegistered" shortDescription="Device already registered." description="Device already registered.">
		<Member name="Device" type="string" description="Device name."/>
	</ErrorCode>
	
	<ErrorCode name="RegisteringDeviceProblem" shortDescription="Registering Device Problem." description="Problem to register the device.">
		<Member name="Device" type="string" description="Device name."/>
	</ErrorCode>
	
	<ErrorCode name="DeviceNotRegistered" shortDescription="Device has not been registered." description="Device has not been registered.">
		<Member name="Device" type="string" description="Device name."/>
	</ErrorCode>
	
	<ErrorCode name="StartMonitoringProblem" shortDescription="Could not start monitoring." description="Could not start monitoring the device">
		<Member name="Device" type="string" description="Device name."/>
	</ErrorCode>
	
	<ErrorCode name="StopMonitoringProblem" shortDescription="Could not stop monitoring." description="Could not stop monitoring the device">
		<Member name="Device" type="string" description="Device name."/>
	</ErrorCode>
	
	<ErrorCode name="NonExistentProperty" shortDescription="Property does not exist." description="The property does not exist.">
		<Member name="Property" type="string" description="Property name."/>
	</ErrorCode>
	
	<ErrorCode name="NonSupportedType" shortDescription="Non supported type." description="Non supported property type.">
	    <Member name="Property" type="string" description="Property name."/>
		<Member name="PropertyType" type="string" description="Property type."/>
	</ErrorCode>
	
	<ErrorCode name="NotCollocatedComponent" shortDescription="Device not collocated." description="Try to monitor component that's not collocated.">
		<Member name="Component" type="string" description="Component name."/>
	</ErrorCode>

	<!-- =========== Monitor controller errors =========== -->

	<ErrorCode name="CollectorRegistrationFailed" 
	           shortDescription="Failed to register a collector with a blobber." 
	           description="The monitor controller failed to assign the calling monitor collector to any of the blobber components.">
		<Member name="NumberOfBlobbers" type="long" description="The number of blobber components tried to assign the collector to. This may include configured blobbers that are not available at runtime."/>
	</ErrorCode>

</Type>

=== ACS-Community/ACS/Benchmark/components/idl/BenchmarkErrType.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="Alma/ACSError" xsi:schemaLocation="Alma/ACSError ACSError.xsd" 
      name="BenchmarkErrType" 
      type="12" 
      _prefix="alma">
	<Code name="BenchmarkErrTestOK" shortDescription="Test OK" description="Test OK"/>
	<ErrorCode name="BenchmarkErr0" shortDescription="benchmark error 0" description="benchmark error 0"/>
	<ErrorCode name="BenchmarkErr1" shortDescription="benchmark error 1" description="benchmark error 1"/>
	<ErrorCode name="BenchmarkErr2" shortDescription="benchmark error 2" description="benchmark error 2"/>
	<ErrorCode name="BenchmarkErr3" shortDescription="benchmark error 3" description="benchmark error 3"/>
	<ErrorCode name="BenchmarkErr4" shortDescription="benchmark error 4" description="benchmark error 4" _suppressExceptionGeneration="true"/>
	<ErrorCode name="BenchmarkErr5" shortDescription="benchmark error 5" description="benchmark error 5" _suppressExceptionGeneration="true"/>
</Type>

=== ACS-Community/ACS/LGPL/CommonSoftware/acserrTypes/ws/idl/ACSErrTypeCommon.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ACSError.xsd" name="ACSErrTypeCommon" type="10" _prefix="alma">
	<ErrorCode name="FileNotFound" 
	           shortDescription="File couldn't be found" 
                   description="File couldn't be found">
	           <Member name="FileName" type="string" description="File name"/>
	</ErrorCode>
	<ErrorCode name="OutOfBounds" 
	           shortDescription="Out of bounds"
	           description="Out of bounds">
		   <Member name="minValue" 
                           type="string" 
 	                   description="Min value of the bounds."/>
	           <Member name="maxValue" 
		          type="string" 
 	                  description="Max value of the bounds."/>
	            <Member name="requestedValue" 
		          type="string" 
 	                  description="Requested value."/>
	</ErrorCode>
	<ErrorCode name="IOError" shortDescription="Input Output Error" description="Input Output Error"/>
	<ErrorCode name="Unknown" shortDescription="Unknown Error" description="Unknown Error"/>
	<ErrorCode name="NoResources" shortDescription="No Resources" description="No Resources"/>
	<ErrorCode name="MemoryFault" shortDescription="Memory Problem" description="Memory Problem"/>
	<ErrorCode name="CouldntCreateObject" shortDescription="Object couldn't be created" description="Object couldn't be created"/>
	<ErrorCode name="CouldntCreateThread" shortDescription="Thread couldn't be created" description="Thread couldn't be created"/>
	<ErrorCode name="CouldntAccessComponent" shortDescription="Component couldn't be accessed" description="Component couldn't be accessed"/>
	<ErrorCode name="CouldntAccessProperty" shortDescription="Property couldn't be accessed" description="Property couldn't be accessed"/>
	<ErrorCode name="CouldntPerformAction" shortDescription="Action couldn't be performed" description="Action couldn't be performed"/>
	<ErrorCode name="TypeNotFound" shortDescription="Type Not Found" description="Type Not Found"/>
	<ErrorCode name="TypeNotSupported" shortDescription="Type Not Supported" description="Type Not Supported"/>
	<ErrorCode name="CORBAProblem" shortDescription="CORBA Problem" description="CORBA Problem"/>
	<ErrorCode name="IllegalStateEvent" shortDescription="illegal event sent to a state machine" description="illegal event sent to a state machine"/>
	<ErrorCode name="NotImplemented" 
                   shortDescription="Method or feature not implemented" 
                   description="The specified feature is not
		   implemented. If none is specified, the whole method
		   is not implemented.">
 	           <Member name="Feature" 
                           type="string" 
 	                   description="Feature not implemented. Whole method is not specified"/>
	</ErrorCode>
	<ErrorCode name="GenericError" 
                   shortDescription="An error occurred, see ErrorDesc member" 
                   description="An error occurred and no specific
		   error code exists. A description of the error is
		   given in the ErrorDesc member.">
	           <Member name="ErrorDesc" 
                           type="string" 
 	                   description="String describing the error condition"/>
	</ErrorCode>
</Type>

=== ACS-Community/ACS/LGPL/CommonSoftware/acslog/ws/idl/ACSErrTypeTest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Bogdan Jeram (E.S.O.) -->
<Type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="Alma/ACSError" xsi:schemaLocation="Alma/ACSError ACSError.xsd" name="ACSErrTypeTest" type="900902" _prefix="alma">
	<Code name="ACSErrTestOK" shortDescription="Test OK" description="Test OK"/>
	<ErrorCode name="ACSErrTest0" shortDescription="Test error 0" description="Test error 0"/>
	<ErrorCode name="ACSErrTest1" shortDescription="Test error 1" description="Test error 1"/>
	<ErrorCode name="ACSErrTest2" shortDescription="Test error 2" description="Test error 2"/>
	<ErrorCode name="ACSErrTest3" shortDescription="Test error 3" description="Test error 3"/>
	<ErrorCode name="ACSErrTest4" shortDescription="Test error 4" description="Test error 4" _suppressExceptionGeneration="1"/>
	<ErrorCode name="ACSErrTest5" shortDescription="Test error 5" description="Test error 5" _suppressExceptionGeneration="true"/>
</Type>

=== ACS-Community/ACS/ACS/LGPL/CommonSoftware/baciidl/ws/idl/baciErrTypeProperty.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<Type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="Alma/ACSError" xsi:schemaLocation="Alma/ACSError ACSError.xsd" name="baciErrTypeProperty"
type="20" _prefix="alma">
<ErrorCode name="PropertyStaticData"
           shortDescription="Error reading static data"
	   description="Error reading static data"
/>
<ErrorCode name="PropertyCreation"
           shortDescription="Error creating property"
	   description="Error creating the property"
/>
<ErrorCode name="PropertyActivation"
           shortDescription="Error activating property"
	   description="Error activating the property"
/>
<ErrorCode name="PropertySetInitValue"
           shortDescription="Error setting initial value"
	   description="Error setting the intial value of the
	   	   property"
/>
<ErrorCode name="CanNotSetValue" 
           shortDescription="Problem to set value"
	   description="Problem to set value of the property">
           <Member name="Property" 
	           type="string" 
		   description="Property Name."/>
</ErrorCode>
<ErrorCode name="CanNotGetValue" 
           shortDescription="Problem to get value"
	   description="Problem to get value of the property">
	   <Member name="Property" 
	           type="string" 
		   description="Property Name."/>
</ErrorCode>
<ErrorCode name="InvokeActionError" 
           shortDescription="Error in invokeAction"
	   description="Error in invokeAction which performs
	   asynchronous calls"
/>
<ErrorCode name="IncrementError" 
           shortDescription="Increment value error"
	   description="Increment value error"
/>
<ErrorCode name="DecrementError" 
           shortDescription="Decrement value error"
	   description="Decrement value error"
/>
<ErrorCode name="ArchiveMonitorProblem"
           shortDescription="Problem to archive a value"
	   description="Archive monitor could not archive a value of
	   a property."
/>
<ErrorCode name="DisableAlarmsError"
           shortDescription="Failed to disable propagation of Property Alarms"
	   description="Failed to disable the propagation of Property Alarms to the ACS Alarm System because an alarm is already raised."
/>
</Type>
